//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tpm_CalcHistorico.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EST02DB")]
        public string SrvSql {
            get {
                return ((string)(this["SrvSql"]));
            }
            set {
                this["SrvSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TpmMtto")]
        public string BD {
            get {
                return ((string)(this["BD"]));
            }
            set {
                this["BD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TpmManto")]
        public string UserSql {
            get {
                return ((string)(this["UserSql"]));
            }
            set {
                this["UserSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tpmsql2019")]
        public string PwdSql {
            get {
                return ((string)(this["PwdSql"]));
            }
            set {
                this["PwdSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\atkApps\\AtkTpmMantto\\HistCc11205\\Log\\TpmCalcHistLog.txt")]
        public string RutaLog {
            get {
                return ((string)(this["RutaLog"]));
            }
            set {
                this["RutaLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\atkApps\\AtkTpmMantto\\HistCc11205\\Log\\TpmCalcHistBug.txt")]
        public string RutaLogError {
            get {
                return ((string)(this["RutaLogError"]));
            }
            set {
                this["RutaLogError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Planta {
            get {
                return ((int)(this["Planta"]));
            }
            set {
                this["Planta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PREN")]
        public string Departamento {
            get {
                return ((string)(this["Departamento"]));
            }
            set {
                this["Departamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11205")]
        public string CtroCtos {
            get {
                return ((string)(this["CtroCtos"]));
            }
            set {
                this["CtroCtos"] = value;
            }
        }
    }
}
